/*
 * Gourd Recipe Database
 *
 * API for https://github.com/nickysemenza/gourd
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: n@nickysemenza.com
 * Generated by: https://openapi-generator.tech
 */

/// IngredientDetail : An Ingredient



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct IngredientDetail {
    #[serde(rename = "ingredient")]
    pub ingredient: crate::models::Ingredient,
    /// Recipes referencing this ingredient
    #[serde(rename = "recipes", skip_serializing_if = "Option::is_none")]
    pub recipes: Option<Vec<crate::models::RecipeDetail>>,
    /// Ingredients that are equivalent
    #[serde(rename = "children", skip_serializing_if = "Option::is_none")]
    pub children: Option<Vec<crate::models::IngredientDetail>>,
    #[serde(rename = "food", skip_serializing_if = "Option::is_none")]
    pub food: Option<crate::models::Food>,
}

impl IngredientDetail {
    /// An Ingredient
    pub fn new(ingredient: crate::models::Ingredient) -> IngredientDetail {
        IngredientDetail {
            ingredient,
            recipes: None,
            children: None,
            food: None,
        }
    }
}


