/* tslint:disable */
/* eslint-disable */
/**
 * Gourd Recipe Database
 * API for https://github.com/nickysemenza/gourd
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: n@nickysemenza.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ListAllAlbums200Response,
} from '../models';
import {
    ListAllAlbums200ResponseFromJSON,
    ListAllAlbums200ResponseToJSON,
} from '../models';

/**
 * 
 */
export class AlbumsApi extends runtime.BaseAPI {

    /**
     * todo
     * List all albums
     */
    async listAllAlbumsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListAllAlbums200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/albums`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListAllAlbums200ResponseFromJSON(jsonValue));
    }

    /**
     * todo
     * List all albums
     */
    async listAllAlbums(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListAllAlbums200Response> {
        const response = await this.listAllAlbumsRaw(initOverrides);
        return await response.value();
    }

}
