/* tslint:disable */
/* eslint-disable */
/**
 * Gourd Recipe Database
 * API for https://github.com/nickysemenza/gourd
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: n@nickysemenza.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { FoodAttributeFoodAttributeType } from './FoodAttributeFoodAttributeType';
import {
    FoodAttributeFoodAttributeTypeFromJSON,
    FoodAttributeFoodAttributeTypeFromJSONTyped,
    FoodAttributeFoodAttributeTypeToJSON,
} from './FoodAttributeFoodAttributeType';

/**
 * 
 * @export
 * @interface FoodAttribute
 */
export interface FoodAttribute {
    /**
     * 
     * @type {number}
     * @memberof FoodAttribute
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof FoodAttribute
     */
    sequence_number?: number;
    /**
     * 
     * @type {string}
     * @memberof FoodAttribute
     */
    value?: string;
    /**
     * 
     * @type {FoodAttributeFoodAttributeType}
     * @memberof FoodAttribute
     */
    food_attribute_type?: FoodAttributeFoodAttributeType;
}

/**
 * Check if a given object implements the FoodAttribute interface.
 */
export function instanceOfFoodAttribute(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function FoodAttributeFromJSON(json: any): FoodAttribute {
    return FoodAttributeFromJSONTyped(json, false);
}

export function FoodAttributeFromJSONTyped(json: any, ignoreDiscriminator: boolean): FoodAttribute {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'sequence_number': !exists(json, 'sequenceNumber') ? undefined : json['sequenceNumber'],
        'value': !exists(json, 'value') ? undefined : json['value'],
        'food_attribute_type': !exists(json, 'FoodAttributeType') ? undefined : FoodAttributeFoodAttributeTypeFromJSON(json['FoodAttributeType']),
    };
}

export function FoodAttributeToJSON(value?: FoodAttribute | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'sequenceNumber': value.sequence_number,
        'value': value.value,
        'FoodAttributeType': FoodAttributeFoodAttributeTypeToJSON(value.food_attribute_type),
    };
}

