/* tslint:disable */
/* eslint-disable */
/**
 * Gourd Recipe Database
 * API for https://github.com/nickysemenza/gourd
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: n@nickysemenza.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Amount } from './Amount';
import {
    AmountFromJSON,
    AmountFromJSONTyped,
    AmountToJSON,
} from './Amount';
import type { EntitySummary } from './EntitySummary';
import {
    EntitySummaryFromJSON,
    EntitySummaryFromJSONTyped,
    EntitySummaryToJSON,
} from './EntitySummary';

/**
 * todo
 * @export
 * @interface IngredientUsage
 */
export interface IngredientUsage {
    /**
     * multiplier
     * @type {number}
     * @memberof IngredientUsage
     */
    multiplier: number;
    /**
     * multiple amounts to try
     * @type {Array<Amount>}
     * @memberof IngredientUsage
     */
    amounts: Array<Amount>;
    /**
     * mappings of equivalent units
     * @type {Array<EntitySummary>}
     * @memberof IngredientUsage
     */
    required_by: Array<EntitySummary>;
}

/**
 * Check if a given object implements the IngredientUsage interface.
 */
export function instanceOfIngredientUsage(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "multiplier" in value;
    isInstance = isInstance && "amounts" in value;
    isInstance = isInstance && "required_by" in value;

    return isInstance;
}

export function IngredientUsageFromJSON(json: any): IngredientUsage {
    return IngredientUsageFromJSONTyped(json, false);
}

export function IngredientUsageFromJSONTyped(json: any, ignoreDiscriminator: boolean): IngredientUsage {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'multiplier': json['multiplier'],
        'amounts': ((json['amounts'] as Array<any>).map(AmountFromJSON)),
        'required_by': ((json['required_by'] as Array<any>).map(EntitySummaryFromJSON)),
    };
}

export function IngredientUsageToJSON(value?: IngredientUsage | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'multiplier': value.multiplier,
        'amounts': ((value.amounts as Array<any>).map(AmountToJSON)),
        'required_by': ((value.required_by as Array<any>).map(EntitySummaryToJSON)),
    };
}

