/* tslint:disable */
/* eslint-disable */
/**
 * Gourd Recipe Database
 * API for https://github.com/nickysemenza/gourd
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: n@nickysemenza.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    GooglePhoto,
    GooglePhotoFromJSON,
    GooglePhotoFromJSONTyped,
    GooglePhotoToJSON,
    Items,
    ItemsFromJSON,
    ItemsFromJSONTyped,
    ItemsToJSON,
} from './';

/**
 * pages of GooglePhoto
 * @export
 * @interface PaginatedPhotos
 */
export interface PaginatedPhotos {
    /**
     * 
     * @type {Array<GooglePhoto>}
     * @memberof PaginatedPhotos
     */
    photos?: Array<GooglePhoto>;
    /**
     * 
     * @type {Items}
     * @memberof PaginatedPhotos
     */
    meta?: Items;
}

export function PaginatedPhotosFromJSON(json: any): PaginatedPhotos {
    return PaginatedPhotosFromJSONTyped(json, false);
}

export function PaginatedPhotosFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedPhotos {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'photos': !exists(json, 'photos') ? undefined : ((json['photos'] as Array<any>).map(GooglePhotoFromJSON)),
        'meta': !exists(json, 'meta') ? undefined : ItemsFromJSON(json['meta']),
    };
}

export function PaginatedPhotosToJSON(value?: PaginatedPhotos | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'photos': value.photos === undefined ? undefined : ((value.photos as Array<any>).map(GooglePhotoToJSON)),
        'meta': ItemsToJSON(value.meta),
    };
}


