/* tslint:disable */
/* eslint-disable */
/**
 * Gourd Recipe Database
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    SectionIngredient,
    SectionIngredientFromJSON,
    SectionIngredientFromJSONTyped,
    SectionIngredientToJSON,
    SectionInstruction,
    SectionInstructionFromJSON,
    SectionInstructionFromJSONTyped,
    SectionInstructionToJSON,
} from './';

/**
 * A step in the recipe
 * @export
 * @interface RecipeSection
 */
export interface RecipeSection {
    /**
     * id
     * @type {string}
     * @memberof RecipeSection
     */
    id: string;
    /**
     * How many minutes the step takes, approximately (todo - make this a range)
     * @type {number}
     * @memberof RecipeSection
     */
    minutes: number;
    /**
     * x
     * @type {Array<SectionInstruction>}
     * @memberof RecipeSection
     */
    instructions: Array<SectionInstruction>;
    /**
     * x
     * @type {Array<SectionIngredient>}
     * @memberof RecipeSection
     */
    ingredients: Array<SectionIngredient>;
}

export function RecipeSectionFromJSON(json: any): RecipeSection {
    return RecipeSectionFromJSONTyped(json, false);
}

export function RecipeSectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecipeSection {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'minutes': json['minutes'],
        'instructions': ((json['instructions'] as Array<any>).map(SectionInstructionFromJSON)),
        'ingredients': ((json['ingredients'] as Array<any>).map(SectionIngredientFromJSON)),
    };
}

export function RecipeSectionToJSON(value?: RecipeSection | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'minutes': value.minutes,
        'instructions': ((value.instructions as Array<any>).map(SectionInstructionToJSON)),
        'ingredients': ((value.ingredients as Array<any>).map(SectionIngredientToJSON)),
    };
}


