linters:
  enable:
    - megacheck
    - govet
    - unparam
    - sqlclosecheck
    - misspell
    - noctx
    - gocritic
    - bodyclose
    - unused
    - unparam
    - ineffassign
  presets:
    - bugs
    - unused
run:
  timeout: 3m
  skip-dirs:
    - ui
    - rust
