linters:
  enable:
    - dupl
    - gofmt
    - goconst
    - misspell
    - gosec
    - golint
  presets:
    - complexity
    - bugs
    - format
    - style
  disable:
    - wsl
    - godox
    - testpackage
    - lll
    - gomnd
    - scopelint
    - exhaustivestruct
