linters:
  enable:
    - megacheck
    - govet
    - unparam
    - sqlclosecheck
    - misspell
    - noctx
    - gocritic
    - bodyclose
  presets:
    - bugs
    - unused
  disable:
    - gomnd
run:
  timeout: 3m

  skip-dirs:
    - ui
    - rust
