# https://github.com/open-telemetry/opentelemetry-js/blob/main/examples/collector-exporter-node/docker/collector-config.yaml
receivers:
  otlp:
    protocols:
      grpc:
      http:
        cors_allowed_origins:
          - http://*
          - https://*

exporters:
  jaeger:
    endpoint: jaeger:14250
    insecure: true
  prometheus:
    endpoint: "0.0.0.0:9464"

processors:
  batch:

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [jaeger]
      processors: [batch]
    metrics:
      receivers: [otlp]
      exporters: [prometheus]
      processors: [batch]
