FROM ghcr.io/nickysemenza/docker-magick:main
RUN apt-get update
RUN apt-get install -y texlive-latex-base texlive-fonts-recommended texlive-fonts-extra texlive-latex-extra unzip postgresql
RUN which pdflatex
RUN which magick