@rustHostname = http://localhost:8080

@name = codec exxpand
POST {{rustHostname}}/codec/expand
Content-Type: application/json

{
	"meta": {"name":"test"},
	"sections": [{
		"instructions": [],
		"ingredients": ["1 tsp salt", "1 tsp pepper"]
	}]
}

###
