[package]
edition = "2018"
name = "gourd"
version = "0.1.0"

[lib]
path = "src/lib.rs"

[[bin]]
name = "gourd"
path = "src/main.rs"

[dependencies]
actix-http = "3.2"
actix-router = "0.5.1"
actix-web = "4.2"
actix-web-opentelemetry = "0.13.0"
anyhow = "1.0"
clap = "3.2.22"
config = {version = "0.13.2", default-features = false, features = ["yaml"]}
futures = "0.3"
gourd_common = {path = "../common"}
openapi = {path = "../openapi"}
opentelemetry = "0.18.0"
opentelemetry-jaeger = "0.17"
serde = {version = "1.0", features = ["derive"]}
serde-aux = "4.0.0"
serde_derive = "^1.0"
serde_json = "1.0"
tracing = "0.1.36"
tracing-opentelemetry = "0.18.0"
tracing-subscriber = {version = "0.3.15", features=["env-filter"]}
url = "2.3"
recipe-scraper = {git = "https://github.com/nickysemenza/ingredient-parser", branch = "scraper"}


[dev-dependencies]
actix-rt = "2.7.0"

