// Code generated by "stringer -type=Unit -linecomment"; DO NOT EDIT.

package unit

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Gram-0]
	_ = x[Ounce-1]
	_ = x[Liter-2]
	_ = x[Quart-3]
	_ = x[Cup-4]
	_ = x[Teaspoon-5]
	_ = x[Tablespoon-6]
	_ = x[Item-7]
}

const _Unit_name = "gramozliterquuartcputsptbspitem"

var _Unit_index = [...]uint8{0, 4, 6, 11, 17, 20, 23, 27, 31}

func (i Unit) String() string {
	if i < 0 || i >= Unit(len(_Unit_index)-1) {
		return "Unit(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Unit_name[_Unit_index[i]:_Unit_index[i+1]]
}
