version: "3.1"

services:
  db:
    image: postgres:15.3
    restart: always
    ports:
      - "5555:5432"
    environment:
      POSTGRES_USER: gourd
      POSTGRES_PASSWORD: gourd
      POSTGRES_DB: food
    command:
      [
        "postgres",
        "-c",
        "log_min_duration_statement=0",
        "-c",
        "log_destination=stderr",
        "-c",
        "log_line_prefix=%t [%p]:[%l] user=%u, db=%d "
      ]
  jaeger:
    container_name: food-jaeger
    environment:
      - 'COLLECTOR_ZIPKIN_HOST_PORT=:9411'
    command:
      - --memory.max-traces=1000
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - 5778:5778
      - 16686:16686 # UI
      - 14268:14268
      - 9411:9411
    image: "jaegertracing/all-in-one:1.47"
  # Collector
  collector:
    image: otel/opentelemetry-collector:0.81.0
    platform: linux/amd64
    command: [ "--config=/conf/collector-config.yaml" ]
    volumes:
      - ../tooling/dev/collector-config.yaml:/conf/collector-config.yaml
    ports:
      - "9464:9464"
      - "4317:4317"
      - "55680:55680"
      - "55681:55681"
      - "4318:4318"
    depends_on:
      - jaeger
  meilisearch:
    ports:
      - '7700:7700'
    environment:
      - MEILI_MASTER_KEY=FOO
    volumes:
      - '../tmp/meili_data:/meili_data'
    image: 'getmeili/meilisearch:v1.2'
