app = "tracing"
kill_signal = "SIGINT"
kill_timeout = 5

[build]
image = "jaegertracing/all-in-one:latest"

[experimental]
auto_rollback = true

[[services]]
internal_port = 16_686
protocol = "tcp"

[[services.ports]]
handlers = ["http"]
port = 80

[[services.ports]]
handlers = ["tls", "http"]
port = 443

[[services.tcp_checks]]
grace_period = "1s"
interval = "15s"
restart_limit = 0
timeout = "2s"

[services.concurrency]
hard_limit = 25
soft_limit = 20
type = "connections"

[[services]]
internal_port = 14_268
protocol = "tcp"

[services.concurrency]
hard_limit = 25
soft_limit = 20
type = "connections"
