/*
 * Gourd Recipe Database
 *
 * API for https://github.com/nickysemenza/gourd
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: n@nickysemenza.com
 * Generated by: https://openapi-generator.tech
 */

/// MealRecipe : A recipe that's part of a meal (a recipe at a specific amount)



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct MealRecipe {
    /// when it was taken
    #[serde(rename = "multiplier")]
    pub multiplier: f64,
    #[serde(rename = "recipe")]
    pub recipe: Box<crate::models::RecipeDetail>,
}

impl MealRecipe {
    /// A recipe that's part of a meal (a recipe at a specific amount)
    pub fn new(multiplier: f64, recipe: crate::models::RecipeDetail) -> MealRecipe {
        MealRecipe {
            multiplier,
            recipe: Box::new(recipe),
        }
    }
}


