/*
 * Gourd Recipe Database
 *
 * API for https://github.com/nickysemenza/gourd
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: n@nickysemenza.com
 * Generated by: https://openapi-generator.tech
 */

/// SectionInstruction : Instructions in a single section



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SectionInstruction {
    /// id
    #[serde(rename = "id")]
    pub id: String,
    /// instruction
    #[serde(rename = "instruction")]
    pub instruction: String,
}

impl SectionInstruction {
    /// Instructions in a single section
    pub fn new(id: String, instruction: String) -> SectionInstruction {
        SectionInstruction {
            id,
            instruction,
        }
    }
}


