name: e2e-cypress
on: push
jobs:
  test:
    name: e2e Cypress Test
    runs-on: ubuntu-latest
    # container: debian
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: install deps
        run: sudo apt-get install -y texlive-latex-base texlive-fonts-recommended texlive-fonts-extra texlive-latex-extra
      - run: docker-compose pull
      # - uses: satackey/action-docker-layer-caching@v0.0.11
      # continue-on-error: true
      - name: docker-compose build
        run: docker-compose build --parallel
      - run: go mod vendor
      - name: start postgres db
        run: docker-compose up -d db
      - name: migrate db
        run: sleep 5 && make migrate
      - name: start rust server
        run: docker-compose up -d rs
      - name: smoke test rust server
        run: curl -v http://localhost:8080/parse?text=1%20cup
      - name: go integration tests
        run: make integration-test-go
        env:
          MIGRATIONS_DIR: file://../db/migrations
          PDFLATEX_BINARY: /usr/bin/pdflatex
      - uses: codecov/codecov-action@v2
      # - name: run usda import
      # run: docker-compose run usda
      - name: seed db with testdata
        env:
          DB_HOST: localhost
          DB_PORT: 5555
        run: make seed-testdata
      - name: run cypress
        run: docker-compose run ui
      - name: Archive cypress results
        uses: actions/upload-artifact@v2
        with:
          name: cypress-results
          path: /work/ui/cypress/
      - name: Dump docker logs on failure
        if: failure()
        uses: jwalton/gh-docker-logs@v2
