name: e2e-cypress
on: push
jobs:
  test:
    name: e2e Cypress Test
    runs-on: ubuntu-latest
    # container: debian
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: build e2e docker-compose
        run: docker-compose build --parallel
      - name: dl deps
        run: go mod vendor
      - name: start db
        run: docker-compose up -d db
      - name: migrate
        run: sleep 5 && make migrate
      - name: start rs
        run: docker-compose up -d rs
      - name: test rs
        run: curl -v http://localhost:8080/parse?text=1%20cup
      - name: go test integration
        run: make integration-test
      - name: run usda import
        run: docker-compose run usda
      - name: seed db with testdata
        env:
          DB_HOST: localhost
          DB_PORT: 5555
        run: make seed-testdata
      - name: run e2e
        run: docker-compose run ui
      - name: Dump docker logs on failure
        if: failure()
        uses: jwalton/gh-docker-logs@v2
      - name: Archive cypress results
        uses: actions/upload-artifact@v2
        with:
          name: cypress-results
          path: ui/cypress
