name: Go

on:
  push:

jobs:
  golangci:
    name: golang lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2.5.2
        with:
          version: latest
  build:
    name: Go ${{ matrix.go }} test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.17", "1.18.0-beta1"]
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
          stable: ${{ !contains(matrix.go, 'beta') }} # https://github.com/actions/setup-go/issues/176

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get dependencies
        run: go mod vendor
      - name: Test
        run: make unit-cover-go
      - uses: codecov/codecov-action@v2
