// Code generated by SQLBoiler 4.8.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testGphotosAlbums(t *testing.T) {
	t.Parallel()

	query := GphotosAlbums()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testGphotosAlbumsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &GphotosAlbum{}
	if err = randomize.Struct(seed, o, gphotosAlbumDBTypes, true, gphotosAlbumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize GphotosAlbum struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := GphotosAlbums().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testGphotosAlbumsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &GphotosAlbum{}
	if err = randomize.Struct(seed, o, gphotosAlbumDBTypes, true, gphotosAlbumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize GphotosAlbum struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := GphotosAlbums().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := GphotosAlbums().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testGphotosAlbumsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &GphotosAlbum{}
	if err = randomize.Struct(seed, o, gphotosAlbumDBTypes, true, gphotosAlbumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize GphotosAlbum struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := GphotosAlbumSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := GphotosAlbums().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testGphotosAlbumsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &GphotosAlbum{}
	if err = randomize.Struct(seed, o, gphotosAlbumDBTypes, true, gphotosAlbumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize GphotosAlbum struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := GphotosAlbumExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if GphotosAlbum exists: %s", err)
	}
	if !e {
		t.Errorf("Expected GphotosAlbumExists to return true, but got false.")
	}
}

func testGphotosAlbumsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &GphotosAlbum{}
	if err = randomize.Struct(seed, o, gphotosAlbumDBTypes, true, gphotosAlbumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize GphotosAlbum struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	gphotosAlbumFound, err := FindGphotosAlbum(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if gphotosAlbumFound == nil {
		t.Error("want a record, got nil")
	}
}

func testGphotosAlbumsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &GphotosAlbum{}
	if err = randomize.Struct(seed, o, gphotosAlbumDBTypes, true, gphotosAlbumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize GphotosAlbum struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = GphotosAlbums().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testGphotosAlbumsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &GphotosAlbum{}
	if err = randomize.Struct(seed, o, gphotosAlbumDBTypes, true, gphotosAlbumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize GphotosAlbum struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := GphotosAlbums().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testGphotosAlbumsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	gphotosAlbumOne := &GphotosAlbum{}
	gphotosAlbumTwo := &GphotosAlbum{}
	if err = randomize.Struct(seed, gphotosAlbumOne, gphotosAlbumDBTypes, false, gphotosAlbumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize GphotosAlbum struct: %s", err)
	}
	if err = randomize.Struct(seed, gphotosAlbumTwo, gphotosAlbumDBTypes, false, gphotosAlbumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize GphotosAlbum struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = gphotosAlbumOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = gphotosAlbumTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := GphotosAlbums().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testGphotosAlbumsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	gphotosAlbumOne := &GphotosAlbum{}
	gphotosAlbumTwo := &GphotosAlbum{}
	if err = randomize.Struct(seed, gphotosAlbumOne, gphotosAlbumDBTypes, false, gphotosAlbumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize GphotosAlbum struct: %s", err)
	}
	if err = randomize.Struct(seed, gphotosAlbumTwo, gphotosAlbumDBTypes, false, gphotosAlbumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize GphotosAlbum struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = gphotosAlbumOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = gphotosAlbumTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := GphotosAlbums().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func gphotosAlbumBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *GphotosAlbum) error {
	*o = GphotosAlbum{}
	return nil
}

func gphotosAlbumAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *GphotosAlbum) error {
	*o = GphotosAlbum{}
	return nil
}

func gphotosAlbumAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *GphotosAlbum) error {
	*o = GphotosAlbum{}
	return nil
}

func gphotosAlbumBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *GphotosAlbum) error {
	*o = GphotosAlbum{}
	return nil
}

func gphotosAlbumAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *GphotosAlbum) error {
	*o = GphotosAlbum{}
	return nil
}

func gphotosAlbumBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *GphotosAlbum) error {
	*o = GphotosAlbum{}
	return nil
}

func gphotosAlbumAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *GphotosAlbum) error {
	*o = GphotosAlbum{}
	return nil
}

func gphotosAlbumBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *GphotosAlbum) error {
	*o = GphotosAlbum{}
	return nil
}

func gphotosAlbumAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *GphotosAlbum) error {
	*o = GphotosAlbum{}
	return nil
}

func testGphotosAlbumsHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &GphotosAlbum{}
	o := &GphotosAlbum{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, gphotosAlbumDBTypes, false); err != nil {
		t.Errorf("Unable to randomize GphotosAlbum object: %s", err)
	}

	AddGphotosAlbumHook(boil.BeforeInsertHook, gphotosAlbumBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	gphotosAlbumBeforeInsertHooks = []GphotosAlbumHook{}

	AddGphotosAlbumHook(boil.AfterInsertHook, gphotosAlbumAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	gphotosAlbumAfterInsertHooks = []GphotosAlbumHook{}

	AddGphotosAlbumHook(boil.AfterSelectHook, gphotosAlbumAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	gphotosAlbumAfterSelectHooks = []GphotosAlbumHook{}

	AddGphotosAlbumHook(boil.BeforeUpdateHook, gphotosAlbumBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	gphotosAlbumBeforeUpdateHooks = []GphotosAlbumHook{}

	AddGphotosAlbumHook(boil.AfterUpdateHook, gphotosAlbumAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	gphotosAlbumAfterUpdateHooks = []GphotosAlbumHook{}

	AddGphotosAlbumHook(boil.BeforeDeleteHook, gphotosAlbumBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	gphotosAlbumBeforeDeleteHooks = []GphotosAlbumHook{}

	AddGphotosAlbumHook(boil.AfterDeleteHook, gphotosAlbumAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	gphotosAlbumAfterDeleteHooks = []GphotosAlbumHook{}

	AddGphotosAlbumHook(boil.BeforeUpsertHook, gphotosAlbumBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	gphotosAlbumBeforeUpsertHooks = []GphotosAlbumHook{}

	AddGphotosAlbumHook(boil.AfterUpsertHook, gphotosAlbumAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	gphotosAlbumAfterUpsertHooks = []GphotosAlbumHook{}
}

func testGphotosAlbumsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &GphotosAlbum{}
	if err = randomize.Struct(seed, o, gphotosAlbumDBTypes, true, gphotosAlbumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize GphotosAlbum struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := GphotosAlbums().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testGphotosAlbumsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &GphotosAlbum{}
	if err = randomize.Struct(seed, o, gphotosAlbumDBTypes, true); err != nil {
		t.Errorf("Unable to randomize GphotosAlbum struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(gphotosAlbumColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := GphotosAlbums().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testGphotosAlbumToManyAlbumGphotosPhotos(t *testing.T) {
	var err error
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a GphotosAlbum
	var b, c GphotosPhoto

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, gphotosAlbumDBTypes, true, gphotosAlbumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize GphotosAlbum struct: %s", err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = randomize.Struct(seed, &b, gphotosPhotoDBTypes, false, gphotosPhotoColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, gphotosPhotoDBTypes, false, gphotosPhotoColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}

	b.AlbumID = a.ID
	c.AlbumID = a.ID

	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := a.AlbumGphotosPhotos().All(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	bFound, cFound := false, false
	for _, v := range check {
		if v.AlbumID == b.AlbumID {
			bFound = true
		}
		if v.AlbumID == c.AlbumID {
			cFound = true
		}
	}

	if !bFound {
		t.Error("expected to find b")
	}
	if !cFound {
		t.Error("expected to find c")
	}

	slice := GphotosAlbumSlice{&a}
	if err = a.L.LoadAlbumGphotosPhotos(ctx, tx, false, (*[]*GphotosAlbum)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.AlbumGphotosPhotos); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	a.R.AlbumGphotosPhotos = nil
	if err = a.L.LoadAlbumGphotosPhotos(ctx, tx, true, &a, nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.AlbumGphotosPhotos); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	if t.Failed() {
		t.Logf("%#v", check)
	}
}

func testGphotosAlbumToManyAddOpAlbumGphotosPhotos(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a GphotosAlbum
	var b, c, d, e GphotosPhoto

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, gphotosAlbumDBTypes, false, strmangle.SetComplement(gphotosAlbumPrimaryKeyColumns, gphotosAlbumColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*GphotosPhoto{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, gphotosPhotoDBTypes, false, strmangle.SetComplement(gphotosPhotoPrimaryKeyColumns, gphotosPhotoColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	foreignersSplitByInsertion := [][]*GphotosPhoto{
		{&b, &c},
		{&d, &e},
	}

	for i, x := range foreignersSplitByInsertion {
		err = a.AddAlbumGphotosPhotos(ctx, tx, i != 0, x...)
		if err != nil {
			t.Fatal(err)
		}

		first := x[0]
		second := x[1]

		if a.ID != first.AlbumID {
			t.Error("foreign key was wrong value", a.ID, first.AlbumID)
		}
		if a.ID != second.AlbumID {
			t.Error("foreign key was wrong value", a.ID, second.AlbumID)
		}

		if first.R.Album != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}
		if second.R.Album != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}

		if a.R.AlbumGphotosPhotos[i*2] != first {
			t.Error("relationship struct slice not set to correct value")
		}
		if a.R.AlbumGphotosPhotos[i*2+1] != second {
			t.Error("relationship struct slice not set to correct value")
		}

		count, err := a.AlbumGphotosPhotos().Count(ctx, tx)
		if err != nil {
			t.Fatal(err)
		}
		if want := int64((i + 1) * 2); count != want {
			t.Error("want", want, "got", count)
		}
	}
}

func testGphotosAlbumsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &GphotosAlbum{}
	if err = randomize.Struct(seed, o, gphotosAlbumDBTypes, true, gphotosAlbumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize GphotosAlbum struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testGphotosAlbumsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &GphotosAlbum{}
	if err = randomize.Struct(seed, o, gphotosAlbumDBTypes, true, gphotosAlbumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize GphotosAlbum struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := GphotosAlbumSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testGphotosAlbumsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &GphotosAlbum{}
	if err = randomize.Struct(seed, o, gphotosAlbumDBTypes, true, gphotosAlbumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize GphotosAlbum struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := GphotosAlbums().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	gphotosAlbumDBTypes = map[string]string{`ID`: `text`, `Usecase`: `text`}
	_                   = bytes.MinRead
)

func testGphotosAlbumsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(gphotosAlbumPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(gphotosAlbumAllColumns) == len(gphotosAlbumPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &GphotosAlbum{}
	if err = randomize.Struct(seed, o, gphotosAlbumDBTypes, true, gphotosAlbumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize GphotosAlbum struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := GphotosAlbums().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, gphotosAlbumDBTypes, true, gphotosAlbumPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize GphotosAlbum struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testGphotosAlbumsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(gphotosAlbumAllColumns) == len(gphotosAlbumPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &GphotosAlbum{}
	if err = randomize.Struct(seed, o, gphotosAlbumDBTypes, true, gphotosAlbumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize GphotosAlbum struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := GphotosAlbums().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, gphotosAlbumDBTypes, true, gphotosAlbumPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize GphotosAlbum struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(gphotosAlbumAllColumns, gphotosAlbumPrimaryKeyColumns) {
		fields = gphotosAlbumAllColumns
	} else {
		fields = strmangle.SetComplement(
			gphotosAlbumAllColumns,
			gphotosAlbumPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := GphotosAlbumSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testGphotosAlbumsUpsert(t *testing.T) {
	t.Parallel()

	if len(gphotosAlbumAllColumns) == len(gphotosAlbumPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := GphotosAlbum{}
	if err = randomize.Struct(seed, &o, gphotosAlbumDBTypes, true); err != nil {
		t.Errorf("Unable to randomize GphotosAlbum struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert GphotosAlbum: %s", err)
	}

	count, err := GphotosAlbums().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, gphotosAlbumDBTypes, false, gphotosAlbumPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize GphotosAlbum struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert GphotosAlbum: %s", err)
	}

	count, err = GphotosAlbums().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
