// Code generated by SQLBoiler 4.8.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("GphotosAlbums", testGphotosAlbumsUpsert)

	t.Run("GphotosPhotos", testGphotosPhotosUpsert)

	t.Run("Images", testImagesUpsert)

	t.Run("IngredientUnits", testIngredientUnitsUpsert)

	t.Run("Ingredients", testIngredientsUpsert)

	t.Run("KVS", testKVSUpsert)

	t.Run("MealGphotos", testMealGphotosUpsert)

	t.Run("MealRecipes", testMealRecipesUpsert)

	t.Run("Meals", testMealsUpsert)

	t.Run("NotionImages", testNotionImagesUpsert)

	t.Run("NotionRecipes", testNotionRecipesUpsert)

	t.Run("RecipeDetails", testRecipeDetailsUpsert)

	t.Run("RecipeSectionIngredients", testRecipeSectionIngredientsUpsert)

	t.Run("RecipeSectionInstructions", testRecipeSectionInstructionsUpsert)

	t.Run("RecipeSections", testRecipeSectionsUpsert)

	t.Run("Recipes", testRecipesUpsert)

	t.Run("SchemaMigrations", testSchemaMigrationsUpsert)

	t.Run("UsdaAgriculturalAcquisitions", testUsdaAgriculturalAcquisitionsUpsert)

	t.Run("UsdaBrandedFoods", testUsdaBrandedFoodsUpsert)

	t.Run("UsdaFoods", testUsdaFoodsUpsert)

	t.Run("UsdaFoodAttributes", testUsdaFoodAttributesUpsert)

	t.Run("UsdaFoodAttributeTypes", testUsdaFoodAttributeTypesUpsert)

	t.Run("UsdaFoodCalorieConversionFactors", testUsdaFoodCalorieConversionFactorsUpsert)

	t.Run("UsdaFoodCategories", testUsdaFoodCategoriesUpsert)

	t.Run("UsdaFoodComponents", testUsdaFoodComponentsUpsert)

	t.Run("UsdaFoodNutrients", testUsdaFoodNutrientsUpsert)

	t.Run("UsdaFoodNutrientConversionFactors", testUsdaFoodNutrientConversionFactorsUpsert)

	t.Run("UsdaFoodNutrientDerivations", testUsdaFoodNutrientDerivationsUpsert)

	t.Run("UsdaFoodNutrientSources", testUsdaFoodNutrientSourcesUpsert)

	t.Run("UsdaFoodPortions", testUsdaFoodPortionsUpsert)

	t.Run("UsdaFoodProteinConversionFactors", testUsdaFoodProteinConversionFactorsUpsert)

	t.Run("UsdaFoundationFoods", testUsdaFoundationFoodsUpsert)

	t.Run("UsdaInputFoods", testUsdaInputFoodsUpsert)

	t.Run("UsdaLabMethods", testUsdaLabMethodsUpsert)

	t.Run("UsdaLabMethodCodes", testUsdaLabMethodCodesUpsert)

	t.Run("UsdaLabMethodNutrients", testUsdaLabMethodNutrientsUpsert)

	t.Run("UsdaMarketAcquisitions", testUsdaMarketAcquisitionsUpsert)

	t.Run("UsdaMeasureUnits", testUsdaMeasureUnitsUpsert)

	t.Run("UsdaNutrients", testUsdaNutrientsUpsert)

	t.Run("UsdaNutrientIncomingNames", testUsdaNutrientIncomingNamesUpsert)

	t.Run("UsdaRetentionFactors", testUsdaRetentionFactorsUpsert)

	t.Run("UsdaSampleFoods", testUsdaSampleFoodsUpsert)

	t.Run("UsdaSRLegacyFoods", testUsdaSRLegacyFoodsUpsert)

	t.Run("UsdaSubSampleFoods", testUsdaSubSampleFoodsUpsert)

	t.Run("UsdaSubSampleResults", testUsdaSubSampleResultsUpsert)

	t.Run("UsdaSurveyFNDDSFoods", testUsdaSurveyFNDDSFoodsUpsert)

	t.Run("UsdaWweiaFoodCategories", testUsdaWweiaFoodCategoriesUpsert)
}
