// Code generated by SQLBoiler 4.8.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testUsdaFoodNutrientSources(t *testing.T) {
	t.Parallel()

	query := UsdaFoodNutrientSources()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testUsdaFoodNutrientSourcesDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UsdaFoodNutrientSource{}
	if err = randomize.Struct(seed, o, usdaFoodNutrientSourceDBTypes, true, usdaFoodNutrientSourceColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UsdaFoodNutrientSource struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := UsdaFoodNutrientSources().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testUsdaFoodNutrientSourcesQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UsdaFoodNutrientSource{}
	if err = randomize.Struct(seed, o, usdaFoodNutrientSourceDBTypes, true, usdaFoodNutrientSourceColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UsdaFoodNutrientSource struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := UsdaFoodNutrientSources().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := UsdaFoodNutrientSources().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testUsdaFoodNutrientSourcesSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UsdaFoodNutrientSource{}
	if err = randomize.Struct(seed, o, usdaFoodNutrientSourceDBTypes, true, usdaFoodNutrientSourceColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UsdaFoodNutrientSource struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := UsdaFoodNutrientSourceSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := UsdaFoodNutrientSources().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testUsdaFoodNutrientSourcesExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UsdaFoodNutrientSource{}
	if err = randomize.Struct(seed, o, usdaFoodNutrientSourceDBTypes, true, usdaFoodNutrientSourceColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UsdaFoodNutrientSource struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := UsdaFoodNutrientSourceExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if UsdaFoodNutrientSource exists: %s", err)
	}
	if !e {
		t.Errorf("Expected UsdaFoodNutrientSourceExists to return true, but got false.")
	}
}

func testUsdaFoodNutrientSourcesFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UsdaFoodNutrientSource{}
	if err = randomize.Struct(seed, o, usdaFoodNutrientSourceDBTypes, true, usdaFoodNutrientSourceColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UsdaFoodNutrientSource struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	usdaFoodNutrientSourceFound, err := FindUsdaFoodNutrientSource(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if usdaFoodNutrientSourceFound == nil {
		t.Error("want a record, got nil")
	}
}

func testUsdaFoodNutrientSourcesBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UsdaFoodNutrientSource{}
	if err = randomize.Struct(seed, o, usdaFoodNutrientSourceDBTypes, true, usdaFoodNutrientSourceColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UsdaFoodNutrientSource struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = UsdaFoodNutrientSources().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testUsdaFoodNutrientSourcesOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UsdaFoodNutrientSource{}
	if err = randomize.Struct(seed, o, usdaFoodNutrientSourceDBTypes, true, usdaFoodNutrientSourceColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UsdaFoodNutrientSource struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := UsdaFoodNutrientSources().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testUsdaFoodNutrientSourcesAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	usdaFoodNutrientSourceOne := &UsdaFoodNutrientSource{}
	usdaFoodNutrientSourceTwo := &UsdaFoodNutrientSource{}
	if err = randomize.Struct(seed, usdaFoodNutrientSourceOne, usdaFoodNutrientSourceDBTypes, false, usdaFoodNutrientSourceColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UsdaFoodNutrientSource struct: %s", err)
	}
	if err = randomize.Struct(seed, usdaFoodNutrientSourceTwo, usdaFoodNutrientSourceDBTypes, false, usdaFoodNutrientSourceColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UsdaFoodNutrientSource struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = usdaFoodNutrientSourceOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = usdaFoodNutrientSourceTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := UsdaFoodNutrientSources().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testUsdaFoodNutrientSourcesCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	usdaFoodNutrientSourceOne := &UsdaFoodNutrientSource{}
	usdaFoodNutrientSourceTwo := &UsdaFoodNutrientSource{}
	if err = randomize.Struct(seed, usdaFoodNutrientSourceOne, usdaFoodNutrientSourceDBTypes, false, usdaFoodNutrientSourceColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UsdaFoodNutrientSource struct: %s", err)
	}
	if err = randomize.Struct(seed, usdaFoodNutrientSourceTwo, usdaFoodNutrientSourceDBTypes, false, usdaFoodNutrientSourceColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UsdaFoodNutrientSource struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = usdaFoodNutrientSourceOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = usdaFoodNutrientSourceTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := UsdaFoodNutrientSources().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func usdaFoodNutrientSourceBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *UsdaFoodNutrientSource) error {
	*o = UsdaFoodNutrientSource{}
	return nil
}

func usdaFoodNutrientSourceAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *UsdaFoodNutrientSource) error {
	*o = UsdaFoodNutrientSource{}
	return nil
}

func usdaFoodNutrientSourceAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *UsdaFoodNutrientSource) error {
	*o = UsdaFoodNutrientSource{}
	return nil
}

func usdaFoodNutrientSourceBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *UsdaFoodNutrientSource) error {
	*o = UsdaFoodNutrientSource{}
	return nil
}

func usdaFoodNutrientSourceAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *UsdaFoodNutrientSource) error {
	*o = UsdaFoodNutrientSource{}
	return nil
}

func usdaFoodNutrientSourceBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *UsdaFoodNutrientSource) error {
	*o = UsdaFoodNutrientSource{}
	return nil
}

func usdaFoodNutrientSourceAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *UsdaFoodNutrientSource) error {
	*o = UsdaFoodNutrientSource{}
	return nil
}

func usdaFoodNutrientSourceBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *UsdaFoodNutrientSource) error {
	*o = UsdaFoodNutrientSource{}
	return nil
}

func usdaFoodNutrientSourceAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *UsdaFoodNutrientSource) error {
	*o = UsdaFoodNutrientSource{}
	return nil
}

func testUsdaFoodNutrientSourcesHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &UsdaFoodNutrientSource{}
	o := &UsdaFoodNutrientSource{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, usdaFoodNutrientSourceDBTypes, false); err != nil {
		t.Errorf("Unable to randomize UsdaFoodNutrientSource object: %s", err)
	}

	AddUsdaFoodNutrientSourceHook(boil.BeforeInsertHook, usdaFoodNutrientSourceBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	usdaFoodNutrientSourceBeforeInsertHooks = []UsdaFoodNutrientSourceHook{}

	AddUsdaFoodNutrientSourceHook(boil.AfterInsertHook, usdaFoodNutrientSourceAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	usdaFoodNutrientSourceAfterInsertHooks = []UsdaFoodNutrientSourceHook{}

	AddUsdaFoodNutrientSourceHook(boil.AfterSelectHook, usdaFoodNutrientSourceAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	usdaFoodNutrientSourceAfterSelectHooks = []UsdaFoodNutrientSourceHook{}

	AddUsdaFoodNutrientSourceHook(boil.BeforeUpdateHook, usdaFoodNutrientSourceBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	usdaFoodNutrientSourceBeforeUpdateHooks = []UsdaFoodNutrientSourceHook{}

	AddUsdaFoodNutrientSourceHook(boil.AfterUpdateHook, usdaFoodNutrientSourceAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	usdaFoodNutrientSourceAfterUpdateHooks = []UsdaFoodNutrientSourceHook{}

	AddUsdaFoodNutrientSourceHook(boil.BeforeDeleteHook, usdaFoodNutrientSourceBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	usdaFoodNutrientSourceBeforeDeleteHooks = []UsdaFoodNutrientSourceHook{}

	AddUsdaFoodNutrientSourceHook(boil.AfterDeleteHook, usdaFoodNutrientSourceAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	usdaFoodNutrientSourceAfterDeleteHooks = []UsdaFoodNutrientSourceHook{}

	AddUsdaFoodNutrientSourceHook(boil.BeforeUpsertHook, usdaFoodNutrientSourceBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	usdaFoodNutrientSourceBeforeUpsertHooks = []UsdaFoodNutrientSourceHook{}

	AddUsdaFoodNutrientSourceHook(boil.AfterUpsertHook, usdaFoodNutrientSourceAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	usdaFoodNutrientSourceAfterUpsertHooks = []UsdaFoodNutrientSourceHook{}
}

func testUsdaFoodNutrientSourcesInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UsdaFoodNutrientSource{}
	if err = randomize.Struct(seed, o, usdaFoodNutrientSourceDBTypes, true, usdaFoodNutrientSourceColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UsdaFoodNutrientSource struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := UsdaFoodNutrientSources().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testUsdaFoodNutrientSourcesInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UsdaFoodNutrientSource{}
	if err = randomize.Struct(seed, o, usdaFoodNutrientSourceDBTypes, true); err != nil {
		t.Errorf("Unable to randomize UsdaFoodNutrientSource struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(usdaFoodNutrientSourceColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := UsdaFoodNutrientSources().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testUsdaFoodNutrientSourceToManySourceUsdaFoodNutrientDerivations(t *testing.T) {
	var err error
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a UsdaFoodNutrientSource
	var b, c UsdaFoodNutrientDerivation

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, usdaFoodNutrientSourceDBTypes, true, usdaFoodNutrientSourceColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UsdaFoodNutrientSource struct: %s", err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = randomize.Struct(seed, &b, usdaFoodNutrientDerivationDBTypes, false, usdaFoodNutrientDerivationColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, usdaFoodNutrientDerivationDBTypes, false, usdaFoodNutrientDerivationColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}

	queries.Assign(&b.SourceID, a.ID)
	queries.Assign(&c.SourceID, a.ID)
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := a.SourceUsdaFoodNutrientDerivations().All(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	bFound, cFound := false, false
	for _, v := range check {
		if queries.Equal(v.SourceID, b.SourceID) {
			bFound = true
		}
		if queries.Equal(v.SourceID, c.SourceID) {
			cFound = true
		}
	}

	if !bFound {
		t.Error("expected to find b")
	}
	if !cFound {
		t.Error("expected to find c")
	}

	slice := UsdaFoodNutrientSourceSlice{&a}
	if err = a.L.LoadSourceUsdaFoodNutrientDerivations(ctx, tx, false, (*[]*UsdaFoodNutrientSource)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.SourceUsdaFoodNutrientDerivations); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	a.R.SourceUsdaFoodNutrientDerivations = nil
	if err = a.L.LoadSourceUsdaFoodNutrientDerivations(ctx, tx, true, &a, nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.SourceUsdaFoodNutrientDerivations); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	if t.Failed() {
		t.Logf("%#v", check)
	}
}

func testUsdaFoodNutrientSourceToManyAddOpSourceUsdaFoodNutrientDerivations(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a UsdaFoodNutrientSource
	var b, c, d, e UsdaFoodNutrientDerivation

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, usdaFoodNutrientSourceDBTypes, false, strmangle.SetComplement(usdaFoodNutrientSourcePrimaryKeyColumns, usdaFoodNutrientSourceColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*UsdaFoodNutrientDerivation{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, usdaFoodNutrientDerivationDBTypes, false, strmangle.SetComplement(usdaFoodNutrientDerivationPrimaryKeyColumns, usdaFoodNutrientDerivationColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	foreignersSplitByInsertion := [][]*UsdaFoodNutrientDerivation{
		{&b, &c},
		{&d, &e},
	}

	for i, x := range foreignersSplitByInsertion {
		err = a.AddSourceUsdaFoodNutrientDerivations(ctx, tx, i != 0, x...)
		if err != nil {
			t.Fatal(err)
		}

		first := x[0]
		second := x[1]

		if !queries.Equal(a.ID, first.SourceID) {
			t.Error("foreign key was wrong value", a.ID, first.SourceID)
		}
		if !queries.Equal(a.ID, second.SourceID) {
			t.Error("foreign key was wrong value", a.ID, second.SourceID)
		}

		if first.R.Source != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}
		if second.R.Source != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}

		if a.R.SourceUsdaFoodNutrientDerivations[i*2] != first {
			t.Error("relationship struct slice not set to correct value")
		}
		if a.R.SourceUsdaFoodNutrientDerivations[i*2+1] != second {
			t.Error("relationship struct slice not set to correct value")
		}

		count, err := a.SourceUsdaFoodNutrientDerivations().Count(ctx, tx)
		if err != nil {
			t.Fatal(err)
		}
		if want := int64((i + 1) * 2); count != want {
			t.Error("want", want, "got", count)
		}
	}
}

func testUsdaFoodNutrientSourceToManySetOpSourceUsdaFoodNutrientDerivations(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a UsdaFoodNutrientSource
	var b, c, d, e UsdaFoodNutrientDerivation

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, usdaFoodNutrientSourceDBTypes, false, strmangle.SetComplement(usdaFoodNutrientSourcePrimaryKeyColumns, usdaFoodNutrientSourceColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*UsdaFoodNutrientDerivation{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, usdaFoodNutrientDerivationDBTypes, false, strmangle.SetComplement(usdaFoodNutrientDerivationPrimaryKeyColumns, usdaFoodNutrientDerivationColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err = a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	err = a.SetSourceUsdaFoodNutrientDerivations(ctx, tx, false, &b, &c)
	if err != nil {
		t.Fatal(err)
	}

	count, err := a.SourceUsdaFoodNutrientDerivations().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 2 {
		t.Error("count was wrong:", count)
	}

	err = a.SetSourceUsdaFoodNutrientDerivations(ctx, tx, true, &d, &e)
	if err != nil {
		t.Fatal(err)
	}

	count, err = a.SourceUsdaFoodNutrientDerivations().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 2 {
		t.Error("count was wrong:", count)
	}

	if !queries.IsValuerNil(b.SourceID) {
		t.Error("want b's foreign key value to be nil")
	}
	if !queries.IsValuerNil(c.SourceID) {
		t.Error("want c's foreign key value to be nil")
	}
	if !queries.Equal(a.ID, d.SourceID) {
		t.Error("foreign key was wrong value", a.ID, d.SourceID)
	}
	if !queries.Equal(a.ID, e.SourceID) {
		t.Error("foreign key was wrong value", a.ID, e.SourceID)
	}

	if b.R.Source != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if c.R.Source != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if d.R.Source != &a {
		t.Error("relationship was not added properly to the foreign struct")
	}
	if e.R.Source != &a {
		t.Error("relationship was not added properly to the foreign struct")
	}

	if a.R.SourceUsdaFoodNutrientDerivations[0] != &d {
		t.Error("relationship struct slice not set to correct value")
	}
	if a.R.SourceUsdaFoodNutrientDerivations[1] != &e {
		t.Error("relationship struct slice not set to correct value")
	}
}

func testUsdaFoodNutrientSourceToManyRemoveOpSourceUsdaFoodNutrientDerivations(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a UsdaFoodNutrientSource
	var b, c, d, e UsdaFoodNutrientDerivation

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, usdaFoodNutrientSourceDBTypes, false, strmangle.SetComplement(usdaFoodNutrientSourcePrimaryKeyColumns, usdaFoodNutrientSourceColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*UsdaFoodNutrientDerivation{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, usdaFoodNutrientDerivationDBTypes, false, strmangle.SetComplement(usdaFoodNutrientDerivationPrimaryKeyColumns, usdaFoodNutrientDerivationColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	err = a.AddSourceUsdaFoodNutrientDerivations(ctx, tx, true, foreigners...)
	if err != nil {
		t.Fatal(err)
	}

	count, err := a.SourceUsdaFoodNutrientDerivations().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 4 {
		t.Error("count was wrong:", count)
	}

	err = a.RemoveSourceUsdaFoodNutrientDerivations(ctx, tx, foreigners[:2]...)
	if err != nil {
		t.Fatal(err)
	}

	count, err = a.SourceUsdaFoodNutrientDerivations().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 2 {
		t.Error("count was wrong:", count)
	}

	if !queries.IsValuerNil(b.SourceID) {
		t.Error("want b's foreign key value to be nil")
	}
	if !queries.IsValuerNil(c.SourceID) {
		t.Error("want c's foreign key value to be nil")
	}

	if b.R.Source != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if c.R.Source != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if d.R.Source != &a {
		t.Error("relationship to a should have been preserved")
	}
	if e.R.Source != &a {
		t.Error("relationship to a should have been preserved")
	}

	if len(a.R.SourceUsdaFoodNutrientDerivations) != 2 {
		t.Error("should have preserved two relationships")
	}

	// Removal doesn't do a stable deletion for performance so we have to flip the order
	if a.R.SourceUsdaFoodNutrientDerivations[1] != &d {
		t.Error("relationship to d should have been preserved")
	}
	if a.R.SourceUsdaFoodNutrientDerivations[0] != &e {
		t.Error("relationship to e should have been preserved")
	}
}

func testUsdaFoodNutrientSourcesReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UsdaFoodNutrientSource{}
	if err = randomize.Struct(seed, o, usdaFoodNutrientSourceDBTypes, true, usdaFoodNutrientSourceColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UsdaFoodNutrientSource struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testUsdaFoodNutrientSourcesReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UsdaFoodNutrientSource{}
	if err = randomize.Struct(seed, o, usdaFoodNutrientSourceDBTypes, true, usdaFoodNutrientSourceColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UsdaFoodNutrientSource struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := UsdaFoodNutrientSourceSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testUsdaFoodNutrientSourcesSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UsdaFoodNutrientSource{}
	if err = randomize.Struct(seed, o, usdaFoodNutrientSourceDBTypes, true, usdaFoodNutrientSourceColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UsdaFoodNutrientSource struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := UsdaFoodNutrientSources().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	usdaFoodNutrientSourceDBTypes = map[string]string{`ID`: `integer`, `Code`: `integer`, `Description`: `text`}
	_                             = bytes.MinRead
)

func testUsdaFoodNutrientSourcesUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(usdaFoodNutrientSourcePrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(usdaFoodNutrientSourceAllColumns) == len(usdaFoodNutrientSourcePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &UsdaFoodNutrientSource{}
	if err = randomize.Struct(seed, o, usdaFoodNutrientSourceDBTypes, true, usdaFoodNutrientSourceColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UsdaFoodNutrientSource struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := UsdaFoodNutrientSources().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, usdaFoodNutrientSourceDBTypes, true, usdaFoodNutrientSourcePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize UsdaFoodNutrientSource struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testUsdaFoodNutrientSourcesSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(usdaFoodNutrientSourceAllColumns) == len(usdaFoodNutrientSourcePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &UsdaFoodNutrientSource{}
	if err = randomize.Struct(seed, o, usdaFoodNutrientSourceDBTypes, true, usdaFoodNutrientSourceColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UsdaFoodNutrientSource struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := UsdaFoodNutrientSources().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, usdaFoodNutrientSourceDBTypes, true, usdaFoodNutrientSourcePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize UsdaFoodNutrientSource struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(usdaFoodNutrientSourceAllColumns, usdaFoodNutrientSourcePrimaryKeyColumns) {
		fields = usdaFoodNutrientSourceAllColumns
	} else {
		fields = strmangle.SetComplement(
			usdaFoodNutrientSourceAllColumns,
			usdaFoodNutrientSourcePrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := UsdaFoodNutrientSourceSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testUsdaFoodNutrientSourcesUpsert(t *testing.T) {
	t.Parallel()

	if len(usdaFoodNutrientSourceAllColumns) == len(usdaFoodNutrientSourcePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := UsdaFoodNutrientSource{}
	if err = randomize.Struct(seed, &o, usdaFoodNutrientSourceDBTypes, true); err != nil {
		t.Errorf("Unable to randomize UsdaFoodNutrientSource struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert UsdaFoodNutrientSource: %s", err)
	}

	count, err := UsdaFoodNutrientSources().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, usdaFoodNutrientSourceDBTypes, false, usdaFoodNutrientSourcePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize UsdaFoodNutrientSource struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert UsdaFoodNutrientSource: %s", err)
	}

	count, err = UsdaFoodNutrientSources().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
