// Code generated by SQLBoiler 4.8.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testUsdaSubSampleFoods(t *testing.T) {
	t.Parallel()

	query := UsdaSubSampleFoods()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testUsdaSubSampleFoodsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UsdaSubSampleFood{}
	if err = randomize.Struct(seed, o, usdaSubSampleFoodDBTypes, true, usdaSubSampleFoodColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UsdaSubSampleFood struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := UsdaSubSampleFoods().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testUsdaSubSampleFoodsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UsdaSubSampleFood{}
	if err = randomize.Struct(seed, o, usdaSubSampleFoodDBTypes, true, usdaSubSampleFoodColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UsdaSubSampleFood struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := UsdaSubSampleFoods().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := UsdaSubSampleFoods().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testUsdaSubSampleFoodsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UsdaSubSampleFood{}
	if err = randomize.Struct(seed, o, usdaSubSampleFoodDBTypes, true, usdaSubSampleFoodColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UsdaSubSampleFood struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := UsdaSubSampleFoodSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := UsdaSubSampleFoods().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testUsdaSubSampleFoodsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UsdaSubSampleFood{}
	if err = randomize.Struct(seed, o, usdaSubSampleFoodDBTypes, true, usdaSubSampleFoodColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UsdaSubSampleFood struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := UsdaSubSampleFoodExists(ctx, tx, o.FDCID)
	if err != nil {
		t.Errorf("Unable to check if UsdaSubSampleFood exists: %s", err)
	}
	if !e {
		t.Errorf("Expected UsdaSubSampleFoodExists to return true, but got false.")
	}
}

func testUsdaSubSampleFoodsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UsdaSubSampleFood{}
	if err = randomize.Struct(seed, o, usdaSubSampleFoodDBTypes, true, usdaSubSampleFoodColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UsdaSubSampleFood struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	usdaSubSampleFoodFound, err := FindUsdaSubSampleFood(ctx, tx, o.FDCID)
	if err != nil {
		t.Error(err)
	}

	if usdaSubSampleFoodFound == nil {
		t.Error("want a record, got nil")
	}
}

func testUsdaSubSampleFoodsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UsdaSubSampleFood{}
	if err = randomize.Struct(seed, o, usdaSubSampleFoodDBTypes, true, usdaSubSampleFoodColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UsdaSubSampleFood struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = UsdaSubSampleFoods().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testUsdaSubSampleFoodsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UsdaSubSampleFood{}
	if err = randomize.Struct(seed, o, usdaSubSampleFoodDBTypes, true, usdaSubSampleFoodColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UsdaSubSampleFood struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := UsdaSubSampleFoods().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testUsdaSubSampleFoodsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	usdaSubSampleFoodOne := &UsdaSubSampleFood{}
	usdaSubSampleFoodTwo := &UsdaSubSampleFood{}
	if err = randomize.Struct(seed, usdaSubSampleFoodOne, usdaSubSampleFoodDBTypes, false, usdaSubSampleFoodColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UsdaSubSampleFood struct: %s", err)
	}
	if err = randomize.Struct(seed, usdaSubSampleFoodTwo, usdaSubSampleFoodDBTypes, false, usdaSubSampleFoodColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UsdaSubSampleFood struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = usdaSubSampleFoodOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = usdaSubSampleFoodTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := UsdaSubSampleFoods().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testUsdaSubSampleFoodsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	usdaSubSampleFoodOne := &UsdaSubSampleFood{}
	usdaSubSampleFoodTwo := &UsdaSubSampleFood{}
	if err = randomize.Struct(seed, usdaSubSampleFoodOne, usdaSubSampleFoodDBTypes, false, usdaSubSampleFoodColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UsdaSubSampleFood struct: %s", err)
	}
	if err = randomize.Struct(seed, usdaSubSampleFoodTwo, usdaSubSampleFoodDBTypes, false, usdaSubSampleFoodColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UsdaSubSampleFood struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = usdaSubSampleFoodOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = usdaSubSampleFoodTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := UsdaSubSampleFoods().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func usdaSubSampleFoodBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *UsdaSubSampleFood) error {
	*o = UsdaSubSampleFood{}
	return nil
}

func usdaSubSampleFoodAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *UsdaSubSampleFood) error {
	*o = UsdaSubSampleFood{}
	return nil
}

func usdaSubSampleFoodAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *UsdaSubSampleFood) error {
	*o = UsdaSubSampleFood{}
	return nil
}

func usdaSubSampleFoodBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *UsdaSubSampleFood) error {
	*o = UsdaSubSampleFood{}
	return nil
}

func usdaSubSampleFoodAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *UsdaSubSampleFood) error {
	*o = UsdaSubSampleFood{}
	return nil
}

func usdaSubSampleFoodBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *UsdaSubSampleFood) error {
	*o = UsdaSubSampleFood{}
	return nil
}

func usdaSubSampleFoodAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *UsdaSubSampleFood) error {
	*o = UsdaSubSampleFood{}
	return nil
}

func usdaSubSampleFoodBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *UsdaSubSampleFood) error {
	*o = UsdaSubSampleFood{}
	return nil
}

func usdaSubSampleFoodAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *UsdaSubSampleFood) error {
	*o = UsdaSubSampleFood{}
	return nil
}

func testUsdaSubSampleFoodsHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &UsdaSubSampleFood{}
	o := &UsdaSubSampleFood{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, usdaSubSampleFoodDBTypes, false); err != nil {
		t.Errorf("Unable to randomize UsdaSubSampleFood object: %s", err)
	}

	AddUsdaSubSampleFoodHook(boil.BeforeInsertHook, usdaSubSampleFoodBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	usdaSubSampleFoodBeforeInsertHooks = []UsdaSubSampleFoodHook{}

	AddUsdaSubSampleFoodHook(boil.AfterInsertHook, usdaSubSampleFoodAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	usdaSubSampleFoodAfterInsertHooks = []UsdaSubSampleFoodHook{}

	AddUsdaSubSampleFoodHook(boil.AfterSelectHook, usdaSubSampleFoodAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	usdaSubSampleFoodAfterSelectHooks = []UsdaSubSampleFoodHook{}

	AddUsdaSubSampleFoodHook(boil.BeforeUpdateHook, usdaSubSampleFoodBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	usdaSubSampleFoodBeforeUpdateHooks = []UsdaSubSampleFoodHook{}

	AddUsdaSubSampleFoodHook(boil.AfterUpdateHook, usdaSubSampleFoodAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	usdaSubSampleFoodAfterUpdateHooks = []UsdaSubSampleFoodHook{}

	AddUsdaSubSampleFoodHook(boil.BeforeDeleteHook, usdaSubSampleFoodBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	usdaSubSampleFoodBeforeDeleteHooks = []UsdaSubSampleFoodHook{}

	AddUsdaSubSampleFoodHook(boil.AfterDeleteHook, usdaSubSampleFoodAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	usdaSubSampleFoodAfterDeleteHooks = []UsdaSubSampleFoodHook{}

	AddUsdaSubSampleFoodHook(boil.BeforeUpsertHook, usdaSubSampleFoodBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	usdaSubSampleFoodBeforeUpsertHooks = []UsdaSubSampleFoodHook{}

	AddUsdaSubSampleFoodHook(boil.AfterUpsertHook, usdaSubSampleFoodAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	usdaSubSampleFoodAfterUpsertHooks = []UsdaSubSampleFoodHook{}
}

func testUsdaSubSampleFoodsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UsdaSubSampleFood{}
	if err = randomize.Struct(seed, o, usdaSubSampleFoodDBTypes, true, usdaSubSampleFoodColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UsdaSubSampleFood struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := UsdaSubSampleFoods().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testUsdaSubSampleFoodsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UsdaSubSampleFood{}
	if err = randomize.Struct(seed, o, usdaSubSampleFoodDBTypes, true); err != nil {
		t.Errorf("Unable to randomize UsdaSubSampleFood struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(usdaSubSampleFoodColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := UsdaSubSampleFoods().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testUsdaSubSampleFoodToOneUsdaFoodUsingFDC(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local UsdaSubSampleFood
	var foreign UsdaFood

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, usdaSubSampleFoodDBTypes, false, usdaSubSampleFoodColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UsdaSubSampleFood struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, usdaFoodDBTypes, false, usdaFoodColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UsdaFood struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.FDCID = foreign.FDCID
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.FDC().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.FDCID != foreign.FDCID {
		t.Errorf("want: %v, got %v", foreign.FDCID, check.FDCID)
	}

	slice := UsdaSubSampleFoodSlice{&local}
	if err = local.L.LoadFDC(ctx, tx, false, (*[]*UsdaSubSampleFood)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.FDC == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.FDC = nil
	if err = local.L.LoadFDC(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.FDC == nil {
		t.Error("struct should have been eager loaded")
	}
}

func testUsdaSubSampleFoodToOneUsdaFoodUsingFDCIDOfSampleFoodUsdaFood(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local UsdaSubSampleFood
	var foreign UsdaFood

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, usdaSubSampleFoodDBTypes, true, usdaSubSampleFoodColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UsdaSubSampleFood struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, usdaFoodDBTypes, false, usdaFoodColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UsdaFood struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	queries.Assign(&local.FDCIDOfSampleFood, foreign.FDCID)
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.FDCIDOfSampleFoodUsdaFood().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if !queries.Equal(check.FDCID, foreign.FDCID) {
		t.Errorf("want: %v, got %v", foreign.FDCID, check.FDCID)
	}

	slice := UsdaSubSampleFoodSlice{&local}
	if err = local.L.LoadFDCIDOfSampleFoodUsdaFood(ctx, tx, false, (*[]*UsdaSubSampleFood)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.FDCIDOfSampleFoodUsdaFood == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.FDCIDOfSampleFoodUsdaFood = nil
	if err = local.L.LoadFDCIDOfSampleFoodUsdaFood(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.FDCIDOfSampleFoodUsdaFood == nil {
		t.Error("struct should have been eager loaded")
	}
}

func testUsdaSubSampleFoodToOneSetOpUsdaFoodUsingFDC(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a UsdaSubSampleFood
	var b, c UsdaFood

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, usdaSubSampleFoodDBTypes, false, strmangle.SetComplement(usdaSubSampleFoodPrimaryKeyColumns, usdaSubSampleFoodColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, usdaFoodDBTypes, false, strmangle.SetComplement(usdaFoodPrimaryKeyColumns, usdaFoodColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, usdaFoodDBTypes, false, strmangle.SetComplement(usdaFoodPrimaryKeyColumns, usdaFoodColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*UsdaFood{&b, &c} {
		err = a.SetFDC(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.FDC != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.FDCUsdaSubSampleFood != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.FDCID != x.FDCID {
			t.Error("foreign key was wrong value", a.FDCID)
		}

		if exists, err := UsdaSubSampleFoodExists(ctx, tx, a.FDCID); err != nil {
			t.Fatal(err)
		} else if !exists {
			t.Error("want 'a' to exist")
		}

	}
}
func testUsdaSubSampleFoodToOneSetOpUsdaFoodUsingFDCIDOfSampleFoodUsdaFood(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a UsdaSubSampleFood
	var b, c UsdaFood

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, usdaSubSampleFoodDBTypes, false, strmangle.SetComplement(usdaSubSampleFoodPrimaryKeyColumns, usdaSubSampleFoodColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, usdaFoodDBTypes, false, strmangle.SetComplement(usdaFoodPrimaryKeyColumns, usdaFoodColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, usdaFoodDBTypes, false, strmangle.SetComplement(usdaFoodPrimaryKeyColumns, usdaFoodColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*UsdaFood{&b, &c} {
		err = a.SetFDCIDOfSampleFoodUsdaFood(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.FDCIDOfSampleFoodUsdaFood != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.FDCIDOfSampleFoodUsdaSubSampleFoods[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if !queries.Equal(a.FDCIDOfSampleFood, x.FDCID) {
			t.Error("foreign key was wrong value", a.FDCIDOfSampleFood)
		}

		zero := reflect.Zero(reflect.TypeOf(a.FDCIDOfSampleFood))
		reflect.Indirect(reflect.ValueOf(&a.FDCIDOfSampleFood)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if !queries.Equal(a.FDCIDOfSampleFood, x.FDCID) {
			t.Error("foreign key was wrong value", a.FDCIDOfSampleFood, x.FDCID)
		}
	}
}

func testUsdaSubSampleFoodToOneRemoveOpUsdaFoodUsingFDCIDOfSampleFoodUsdaFood(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a UsdaSubSampleFood
	var b UsdaFood

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, usdaSubSampleFoodDBTypes, false, strmangle.SetComplement(usdaSubSampleFoodPrimaryKeyColumns, usdaSubSampleFoodColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, usdaFoodDBTypes, false, strmangle.SetComplement(usdaFoodPrimaryKeyColumns, usdaFoodColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err = a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = a.SetFDCIDOfSampleFoodUsdaFood(ctx, tx, true, &b); err != nil {
		t.Fatal(err)
	}

	if err = a.RemoveFDCIDOfSampleFoodUsdaFood(ctx, tx, &b); err != nil {
		t.Error("failed to remove relationship")
	}

	count, err := a.FDCIDOfSampleFoodUsdaFood().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 0 {
		t.Error("want no relationships remaining")
	}

	if a.R.FDCIDOfSampleFoodUsdaFood != nil {
		t.Error("R struct entry should be nil")
	}

	if !queries.IsValuerNil(a.FDCIDOfSampleFood) {
		t.Error("foreign key value should be nil")
	}

	if len(b.R.FDCIDOfSampleFoodUsdaSubSampleFoods) != 0 {
		t.Error("failed to remove a from b's relationships")
	}
}

func testUsdaSubSampleFoodsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UsdaSubSampleFood{}
	if err = randomize.Struct(seed, o, usdaSubSampleFoodDBTypes, true, usdaSubSampleFoodColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UsdaSubSampleFood struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testUsdaSubSampleFoodsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UsdaSubSampleFood{}
	if err = randomize.Struct(seed, o, usdaSubSampleFoodDBTypes, true, usdaSubSampleFoodColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UsdaSubSampleFood struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := UsdaSubSampleFoodSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testUsdaSubSampleFoodsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UsdaSubSampleFood{}
	if err = randomize.Struct(seed, o, usdaSubSampleFoodDBTypes, true, usdaSubSampleFoodColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UsdaSubSampleFood struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := UsdaSubSampleFoods().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	usdaSubSampleFoodDBTypes = map[string]string{`FDCID`: `integer`, `FDCIDOfSampleFood`: `integer`}
	_                        = bytes.MinRead
)

func testUsdaSubSampleFoodsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(usdaSubSampleFoodPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(usdaSubSampleFoodAllColumns) == len(usdaSubSampleFoodPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &UsdaSubSampleFood{}
	if err = randomize.Struct(seed, o, usdaSubSampleFoodDBTypes, true, usdaSubSampleFoodColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UsdaSubSampleFood struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := UsdaSubSampleFoods().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, usdaSubSampleFoodDBTypes, true, usdaSubSampleFoodPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize UsdaSubSampleFood struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testUsdaSubSampleFoodsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(usdaSubSampleFoodAllColumns) == len(usdaSubSampleFoodPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &UsdaSubSampleFood{}
	if err = randomize.Struct(seed, o, usdaSubSampleFoodDBTypes, true, usdaSubSampleFoodColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UsdaSubSampleFood struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := UsdaSubSampleFoods().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, usdaSubSampleFoodDBTypes, true, usdaSubSampleFoodPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize UsdaSubSampleFood struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(usdaSubSampleFoodAllColumns, usdaSubSampleFoodPrimaryKeyColumns) {
		fields = usdaSubSampleFoodAllColumns
	} else {
		fields = strmangle.SetComplement(
			usdaSubSampleFoodAllColumns,
			usdaSubSampleFoodPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := UsdaSubSampleFoodSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testUsdaSubSampleFoodsUpsert(t *testing.T) {
	t.Parallel()

	if len(usdaSubSampleFoodAllColumns) == len(usdaSubSampleFoodPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := UsdaSubSampleFood{}
	if err = randomize.Struct(seed, &o, usdaSubSampleFoodDBTypes, true); err != nil {
		t.Errorf("Unable to randomize UsdaSubSampleFood struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert UsdaSubSampleFood: %s", err)
	}

	count, err := UsdaSubSampleFoods().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, usdaSubSampleFoodDBTypes, false, usdaSubSampleFoodPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize UsdaSubSampleFood struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert UsdaSubSampleFood: %s", err)
	}

	count, err = UsdaSubSampleFoods().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
